provider:
  name: coolify

resources:
  private_key:
    create:
      path: /security/keys
      method: POST
    read:
      path: /security/keys/{uuid}
      method: GET
    update:
      path: /security/keys/{uuid}
      method: PATCH
    delete:
      path: /security/keys/{uuid}
      method: DELETE
  server:
    create:
      path: /servers
      method: POST
    read:
      path: /servers/{uuid}
      method: GET
    update:
      path: /servers/{uuid}
      method: PATCH
    delete:
      path: /servers/{uuid}
      method: DELETE
  project:
    create:
      path: /projects
      method: POST
    read:
      path: /projects/{uuid}
      method: GET
    update:
      path: /projects/{uuid}
      method: PATCH
    delete:
      path: /projects/{uuid}
      method: DELETE
  application_envs:
    create:
      path: /applications/{uuid}/envs
      method: POST
    read:
      path: /applications/{uuid}/envs
      method: GET
    update:
      path: /applications/{uuid}/envs/bulk
      method: PATCH
    delete:
      path: /applications/{uuid}/envs/{env_uuid}
      method: DELETE
  service_envs:
    create:
      path: /services/{uuid}/envs
      method: POST
    read:
      path: /services/{uuid}/envs
      method: GET
    update:
      path: /services/{uuid}/envs/bulk
      method: PATCH
    delete:
      path: /services/{uuid}/envs/{env_uuid}
      method: DELETE
  postgresql_database:
    create:
      path: /databases/postgresql
      method: POST
    read:
      path: /databases/{uuid}
      method: GET
    update:
      path: /databases/{uuid}
      method: PATCH
    delete:
      path: /databases/{uuid}
      method: DELETE

data_sources:
  private_keys:
    read:
      path: /security/keys
      method: GET
  private_key:
    read:
      path: /security/keys/{uuid}
      method: GET
  teams:
    read:
      path: /teams
      method: GET
  team:
    read:
      path: /teams/{id}
      method: GET
  server:
    read:
      path: /servers/{uuid}
      method: GET
  servers:
    read:
      path: /servers
      method: GET
  server_resources:
    read:
      path: /servers/{uuid}/resources
      method: GET
  server_domains:
    read:
      path: /servers/{uuid}/domains
      method: GET
  project:
    read:
      path: /projects/{uuid}
      method: GET
  projects:
    read:
      path: /projects
      method: GET
  application:
    read:
      path: /applications/{uuid}
      method: GET
  service:
    read:
      path: /services/{uuid}
      method: GET
